#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hostname
Version  : 3.20
Release  : 14
URL      : http://ftp.us.debian.org/debian/pool/main/h/hostname/hostname_3.20.tar.gz
Source0  : http://ftp.us.debian.org/debian/pool/main/h/hostname/hostname_3.20.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: hostname-bin
Requires: hostname-doc
Patch1: destdir.patch

%description
No detailed description available

%package bin
Summary: bin components for the hostname package.
Group: Binaries

%description bin
bin components for the hostname package.


%package doc
Summary: doc components for the hostname package.
Group: Documentation

%description doc
doc components for the hostname package.


%prep
%setup -q -n hostname
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517507421
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1517507421
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/dnsdomainname
%exclude /usr/bin/domainname
%exclude /usr/bin/nisdomainname
%exclude /usr/bin/ypdomainname
/usr/bin/hostname

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%exclude /usr/share/man/man1/dnsdomainname.1
%exclude /usr/share/man/man1/domainname.1
%exclude /usr/share/man/man1/nisdomainname.1
%exclude /usr/share/man/man1/ypdomainname.1
